API_KEYS={
  "fofa_api_key":"changeme",
  "censys_api_id":"changeme",
  "censys_api_secret":"changeme",
  "hunter_api_key":"changeme",
  "shodan_api_key":"changeme",
  "zoomeye_api_key":"changeme",
  "binaryedge_api_key":"changeme"
}
